name: PHP 7.4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
    
    - name: Generate readme
      run: curl -L https://raw.githubusercontent.com/fumikito/wp-readme/master/wp-readme.php | php
      
    - name: Push readme
      run: |
          git commit -am "Update Readme.txt"
          git push
